image: python:3.6


before-script:
  script:
  - pip install docs/requirements.txt

services:
  - numpy:1.15
  - scipy:0.19
  - coverage:4.5
  
script:
  script:
  - coverage run --source=. tests/test_lc.py 